import { buildAdminPageProps } from './admin-page-props'
import { buildCalendarPageProps } from './calendar-page-props'
import { buildChatPageProps } from './chat-page-props'
import { buildDiagramsPageProps } from './diagrams-page-props'
import { buildFilesPageProps } from './files-page-props'
import { createFilesPageActions } from './files-page-actions'
import { createDiagramsPageActions, createNotesPageActions, createVoicePageActions } from './library-page-actions'
import { buildNotesPageProps } from './notes-page-props'
import { buildSettingsPageProps } from './settings-page-props'
import { buildTasksPageProps } from './tasks-page-props'
import { buildVoicePageProps } from './voice-page-props'
import { createCalendarPageActions, createTasksPageActions } from './workspace-page-actions'

export function useAppPagePropsBundle(context: any) {
  const notePersistenceState: 'saving' | 'unsaved' | 'saved' | null = context.selectedNote
    ? context.noteSaveState === 'saving'
      ? 'saving'
      : context.currentNoteIsDirty()
        ? 'unsaved'
        : 'saved'
    : null

  const notesPageActions = createNotesPageActions({
    selectedFolderPath: context.selectedFolderPath,
    selectedNote: context.selectedNote,
    notesRef: context.notesRef,
    noteDraftRef: context.noteDraftRef,
    adminConfirmDelete: context.adminSettings?.confirm_file_delete ?? true,
    setCustomFolders: context.setCustomFolders,
    setSelectedFolderPath: context.setSelectedFolderPath,
    setNotes: context.setNotes,
    setSelectedNoteId: context.setSelectedNoteId,
    setNoteTitleModalOpen: context.setNoteTitleModalOpen,
    setNoteDrawerOpen: context.setNoteDrawerOpen,
    setActiveNoteSplitter: context.setActiveNoteSplitter,
    setMarkedNotePaths: context.setMarkedNotePaths,
    setDraggingNoteTreePath: context.setDraggingNoteTreePath,
    setNoteTreeDropTargetPath: context.setNoteTreeDropTargetPath,
    setNoteFullscreen: context.setNoteFullscreen,
    setNoteEditorMode: context.setNoteEditorMode,
    setNoteContextMenu: context.setNoteContextMenu,
    setNoteContextSubmenu: context.setNoteContextSubmenu,
    createManagedFolderLocalFirst: context.createManagedFolderLocalFirst,
    createNoteLocalFirst: context.createNoteLocalFirst,
    renameManagedPathLocalFirst: context.renameManagedPathLocalFirst,
    rememberPersistedNotes: context.rememberPersistedNotes,
    refreshFilesTree: context.refreshFilesTree,
    mergeFolderPaths: context.mergeFolderPaths,
    normalizeFolderPath: context.normalizeFolderPath,
    managedPathForNoteFolder: context.managedPathForNoteFolder,
    rebaseFolderEntries: context.rebaseFolderEntries,
    applySelectedNoteMarkdown: context.applySelectedNoteMarkdown,
    currentNoteMarkdown: context.currentNoteMarkdown,
    scheduleNoteDraftBroadcast: context.scheduleNoteDraftBroadcast,
    createNote: context.createNote,
    openNoteInNotes: context.openNoteInNotes,
    beginNoteTreeDrag: context.beginNoteTreeDrag,
    handleNoteTreeDrop: context.handleNoteTreeDrop,
    saveNote: context.saveNote,
    deleteSelectedNote: context.deleteSelectedNote,
    restoreUserDeletedItem: context.restoreUserDeletedItem,
    openShareDialog: context.openShareDialog,
    resourceKeyForNote: context.resourceKeyForNote,
    handleTextareaTabKeyDown: context.handleTextareaTabKeyDown,
    showActionNotice: context.showActionNotice,
  })
  const diagramsPageActions = createDiagramsPageActions({
    selectedDiagram: context.selectedDiagram,
    selectedDiagramId: context.selectedDiagramId,
    setCustomDiagramFolders: context.setCustomDiagramFolders,
    setDiagrams: context.setDiagrams,
    setSelectedDiagramId: context.setSelectedDiagramId,
    setDraggingDiagramTreePath: context.setDraggingDiagramTreePath,
    setDiagramTreeDropTargetPath: context.setDiagramTreeDropTargetPath,
    setActiveDiagramSplitter: context.setActiveDiagramSplitter,
    setDiagramDrawerOpen: context.setDiagramDrawerOpen,
    setDiagramDraft: context.setDiagramDraft,
    createManagedFolderLocalFirst: context.createManagedFolderLocalFirst,
    createDiagramLocalFirst: context.createDiagramLocalFirst,
    renameManagedPathLocalFirst: context.renameManagedPathLocalFirst,
    refreshFilesTree: context.refreshFilesTree,
    createDiagram: context.createDiagram,
    beginDiagramTreeDrag: context.beginDiagramTreeDrag,
    handleDiagramTreeDrop: context.handleDiagramTreeDrop,
    setDiagramMode: context.setDiagramMode,
    saveDiagram: context.saveDiagram,
    persistDiagramXml: context.persistDiagramXml,
    restoreUserDeletedItem: context.restoreUserDeletedItem,
    showActionNotice: context.showActionNotice,
    normalizeDiagramDirectoryPath: context.normalizeDiagramDirectoryPath,
    normalizeDiagramTitlePath: context.normalizeDiagramTitlePath,
    normalizeDiagramFolderPath: context.normalizeDiagramFolderPath,
    managedPathForDiagramFolder: context.managedPathForDiagramFolder,
    diagramIdFromPath: context.diagramIdFromPath,
    rebaseFolderEntries: context.rebaseFolderEntries,
    handleTextareaTabKeyDown: context.handleTextareaTabKeyDown,
    getStandaloneDrawioUrl: context.getStandaloneDrawioUrl,
    standaloneDrawioWindowRef: context.standaloneDrawioWindowRef,
    standaloneDrawioEditingIdRef: context.standaloneDrawioEditingIdRef,
  })
  const voicePageActions = createVoicePageActions({
    memosRef: context.memosRef,
    adminConfirmDelete: context.adminSettings?.confirm_file_delete ?? true,
    setDraggingVoiceTreePath: context.setDraggingVoiceTreePath,
    setVoiceTreeDropTargetPath: context.setVoiceTreeDropTargetPath,
    setActiveVoiceSplitter: context.setActiveVoiceSplitter,
    setVoiceDrawerOpen: context.setVoiceDrawerOpen,
    setMemos: context.setMemos,
    createManagedFolderLocalFirst: context.createManagedFolderLocalFirst,
    renameManagedPathLocalFirst: context.renameManagedPathLocalFirst,
    refreshFilesTree: context.refreshFilesTree,
    beginVoiceTreeDrag: context.beginVoiceTreeDrag,
    handleVoiceTreeDrop: context.handleVoiceTreeDrop,
    openRecorderPanel: context.openRecorderPanel,
    uploadAudioFile: context.uploadAudioFile,
    pollTranscript: context.pollTranscript,
    renamePendingVoiceUploadLocalFirst: context.renamePendingVoiceUploadLocalFirst,
    deletePendingVoiceUploadLocalFirst: context.deletePendingVoiceUploadLocalFirst,
    deleteVoiceMemo: context.deleteVoiceMemo,
    restoreUserDeletedItem: context.restoreUserDeletedItem,
    showActionNotice: context.showActionNotice,
    normalizeVoiceDirectoryPath: context.normalizeVoiceDirectoryPath,
    managedPathForVoiceFolder: context.managedPathForVoiceFolder,
  })

  const notesPageProps = buildNotesPageProps({
    noteFullscreen: context.noteFullscreen,
    notesSectionRef: context.notesSectionRef,
    notePersistenceState,
    selectedNote: context.selectedNote,
    noteSaveState: context.noteSaveState,
    noteDrawerOpen: context.noteDrawerOpen,
    activeNoteSplitter: context.activeNoteSplitter,
    notePaneSize: context.notePaneSize,
    noteManagerRef: context.noteManagerRef,
    selectedNoteFolderPath: context.selectedNoteFolderPath,
    noteTree: context.noteTree,
    notes: context.notes,
    deletedItems: context.deletedItems.filter((item: any) => item.kind === 'note'),
    selectedNoteId: context.selectedNoteId,
    markedPaths: context.markedNotePaths,
    draggingPath: context.draggingNoteTreePath,
    dropTargetPath: context.noteTreeDropTargetPath,
    isCompactViewport: context.isCompactViewport,
    noteTitleModalOpen: context.noteTitleModalOpen,
    noteEditorMode: context.noteEditorMode,
    noteDraft: context.noteDraft,
    activePresence: context.activePresence,
    remoteCursors: context.activeRemoteNoteCursors,
    noteEditorRef: context.noteEditorRef,
    noteContextMenu: context.noteContextMenu,
    noteContextMenuRef: context.noteContextMenuRef,
    noteContextMenuOpenLeft: context.noteContextMenuOpenLeft,
    noteContextSubmenuOpenUp: context.noteContextSubmenuOpenUp,
    noteContextSubmenu: context.noteContextSubmenu,
    noteClipboardText: context.noteClipboardText,
    currentLibraryFolderPath: context.selectedFolderPath,
    ...notesPageActions,
    openNoteContextMenu: context.openNoteContextMenu,
    onCopySelection: context.copyNoteSelection,
    onPasteFromClipboard: context.pasteIntoNoteFromClipboard,
    onSetNoteContextMenu: context.setNoteContextMenu,
    onSetNoteContextSubmenu: context.setNoteContextSubmenu,
  })
  const filesPageActions = createFilesPageActions({
    setCreatingDriveFolder: context.setCreatingDriveFolder,
    setNewDriveFolderName: context.setNewDriveFolderName,
    setPendingDeletePaths: context.setPendingDeletePaths,
    setMarkedFilePaths: context.setMarkedFilePaths,
    setRenamingFilePath: context.setRenamingFilePath,
    setRenameFileName: context.setRenameFileName,
    setConvertingFilePath: context.setConvertingFilePath,
    setFileHelpOpen: context.setFileHelpOpen,
    setDraggingFilePath: context.setDraggingFilePath,
    setDropTargetPath: context.setDropTargetPath,
    setActiveSplitter: context.setActiveSplitter,
    setFileSearchOpen: context.setFileSearchOpen,
    setFileSearchQuery: context.setFileSearchQuery,
    setFileColumnViewOpen: context.setFileColumnViewOpen,
    setActiveFilePath: context.setActiveFilePath,
    createDriveFolderFromSelection: context.createDriveFolderFromSelection,
    deleteManagedPaths: context.deleteManagedPaths,
    renameManagedPath: context.renameManagedPath,
    convertManagedTextFile: context.convertManagedTextFile,
    selectFileTreeNode: context.selectFileTreeNode,
    beginFileDrag: context.beginFileDrag,
    handleDirectoryDrop: context.handleDirectoryDrop,
    toggleFilePreviewPane: context.toggleFilePreviewPane,
    goToParentDirectory: context.goToParentDirectory,
    toggleFileColumnVisibility: context.toggleFileColumnVisibility,
    handleDriveUpload: context.handleDriveUpload,
    beginFileColumnResize: context.beginFileColumnResize,
    renderFileColumnCell: context.renderFileColumnCell,
    openFileNode: context.openFileNode,
    canDeleteFilePath: context.canDeleteFilePath,
    canRenameFilePath: context.canRenameFilePath,
    canConvertFilePath: context.canConvertFilePath,
    requestDeletePaths: context.requestDeletePaths,
    openShareDialog: context.openShareDialog,
    resourceKeyForFilePath: context.resourceKeyForFilePath,
    downloadManagedPath: context.downloadManagedPath,
    beginRenameCurrentFile: context.beginRenameCurrentFile,
  })

  const filesPageProps = buildFilesPageProps({
    creatingDriveFolder: context.creatingDriveFolder,
    newDriveFolderName: context.newDriveFolderName,
    pendingDeletePaths: context.pendingDeletePaths,
    pendingDeleteNodes: context.pendingDeleteNodes,
    renamingFilePath: context.renamingFilePath,
    renameFileName: context.renameFileName,
    convertingFilePath: context.convertingFilePath,
    fileHelpOpen: context.fileHelpOpen,
    fileManagerRef: context.fileManagerRef,
    fileSearchInputRef: context.fileSearchInputRef,
    fileColumnViewRef: context.fileColumnViewRef,
    renameInputRef: context.renameInputRef,
    deleteConfirmButtonRef: context.deleteConfirmButtonRef,
    deleteCancelButtonRef: context.deleteCancelButtonRef,
    activeSplitter: context.activeSplitter,
    filePreviewOpen: context.filePreviewOpen,
    filePaneWidths: context.filePaneWidths,
    filePaneHeights: context.filePaneHeights,
    filesTree: context.filesTree,
    displayNameForFileNode: context.displayNameForFileNode,
    selectedFilePath: context.selectedFilePath,
    activeFileNode: context.activeFileNode,
    markedFilePaths: context.markedFilePaths,
    draggingFilePath: context.draggingFilePath,
    dropTargetPath: context.dropTargetPath,
    currentDirectoryPath: context.currentDirectoryPath,
    trimmedFileSearchQuery: context.trimmedFileSearchQuery,
    fileSearchOpen: context.fileSearchOpen,
    fileSearchQuery: context.fileSearchQuery,
    fileColumnViewOpen: context.fileColumnViewOpen,
    fileColumnVisibility: context.fileColumnVisibility,
    showFileTable: !!context.trimmedFileSearchQuery || context.currentDirectoryNode?.kind === 'directory',
    fileGridTemplateColumns: context.fileGridTemplateColumns,
    visibleFileColumns: context.visibleFileColumns,
    displayedFileNodes: context.displayedFileNodes,
    ...filesPageActions,
  })

  const diagramsPageProps = buildDiagramsPageProps({
    diagramFullscreen: context.diagramFullscreen,
    standaloneDrawio: context.standaloneDrawio,
    diagramManagerRef: context.diagramManagerRef,
    diagramDrawerOpen: context.diagramDrawerOpen,
    activeDiagramSplitter: context.activeDiagramSplitter,
    diagramPaneSize: context.diagramPaneSize,
    diagramTree: context.diagramTree,
    diagramTreeNode: context.diagramsTreeNode,
    diagrams: context.diagrams,
    deletedItems: context.deletedItems.filter((item: any) => item.kind === 'diagram'),
    selectedDiagramId: context.selectedDiagramId,
    selectedDiagramPath: context.selectedDiagramPath,
    markedPaths: context.markedDiagramPaths,
    draggingPath: context.draggingDiagramTreePath,
    dropTargetPath: context.diagramTreeDropTargetPath,
    selectedDiagram: context.selectedDiagram,
    diagramEditorMode: context.diagramEditorMode,
    diagramDraft: context.diagramDraft,
    diagramLoadVersion: context.diagramLoadVersion,
    diagramSourceFormat: context.diagramSourceFormat,
    drawioEditorRef: context.drawioEditorRef,
    ...diagramsPageActions,
    onSetMarkedPaths: context.setMarkedDiagramPaths,
  })

  const voicePageProps = buildVoicePageProps({
    voiceTree: context.voiceTreeNode,
    voiceDrawerOpen: context.voiceDrawerOpen,
    voicePaneSize: context.voicePaneSize,
    activeVoiceSplitter: context.activeVoiceSplitter,
    memos: context.memos,
    deletedItems: context.deletedItems.filter((item: any) => item.kind === 'voice_memo'),
    selectedVoiceMemo: context.selectedVoiceMemo,
    selectedVoicePath: context.selectedVoicePath,
    selectedVoiceMemoSizeBytes: context.selectedVoiceMemoNode?.size_bytes ?? null,
    currentVoiceFolderPath: context.currentVoiceFolderPath,
    recording: context.recording,
    markedPaths: context.markedVoicePaths,
    draggingPath: context.draggingVoiceTreePath,
    dropTargetPath: context.voiceTreeDropTargetPath,
    onSelectVoicePath: context.selectVoicePath,
    onSetMarkedPaths: context.setMarkedVoicePaths,
    ...voicePageActions,
  })

  const calendarPageActions = createCalendarPageActions({
    sessionUserId: context.session?.user.id ?? null,
    googleCalendarConfig: context.googleCalendarConfig,
    calendarConnections: context.calendarConnections,
    selectedCalendarConnectionIds: context.selectedCalendarConnectionIds,
    calendarEvents: context.calendarEvents,
    setSelectedCalendarConnectionIds: context.setSelectedCalendarConnectionIds,
    setCalendarConnections: context.setCalendarConnections,
    setCalendarEvents: context.setCalendarEvents,
    createLocalCalendarConnectionLocalFirst: context.createLocalCalendarConnectionLocalFirst,
    renameCalendarConnectionLocalFirst: context.renameCalendarConnectionLocalFirst,
    deleteCalendarConnectionLocalFirst: context.deleteCalendarConnectionLocalFirst,
    createCalendarEventLocalFirst: context.createCalendarEventLocalFirst,
    updateCalendarEventLocalFirst: context.updateCalendarEventLocalFirst,
    deleteCalendarEventLocalFirst: context.deleteCalendarEventLocalFirst,
    refreshCalendarConnections: context.refreshCalendarConnections,
    refreshCalendarEvents: context.refreshCalendarEvents,
    openShareDialog: context.openShareDialog,
    resourceKeyForCalendar: context.resourceKeyForCalendar,
    showActionNotice: context.showActionNotice,
  })
  const tasksPageActions = createTasksPageActions({
    tasks: context.tasks,
    selectedTaskId: context.selectedTaskId,
    selectedCalendarConnectionIds: context.selectedCalendarConnectionIds,
    setTasks: context.setTasks,
    setSelectedTaskId: context.setSelectedTaskId,
    setCalendarEvents: context.setCalendarEvents,
    createTaskLocalFirst: context.createTaskLocalFirst,
    updateTaskLocalFirst: context.updateTaskLocalFirst,
    deleteTaskLocalFirst: context.deleteTaskLocalFirst,
    refreshTasks: context.refreshTasks,
    refreshCalendarEvents: context.refreshCalendarEvents,
    showActionNotice: context.showActionNotice,
  })
  const calendarPageProps = buildCalendarPageProps({
    googleConfig: context.googleCalendarConfig,
    connections: context.calendarConnections,
    selectedConnectionIds: context.selectedCalendarConnectionIds,
    events: context.calendarEvents,
    ...calendarPageActions,
  })

  const tasksPageProps = buildTasksPageProps({
    tasks: context.tasks,
    selectedTaskId: context.selectedTaskId,
    calendars: context.calendarConnections,
    ...tasksPageActions,
  })

  const chatPageProps = buildChatPageProps({
    chatManagerRef: context.chatManagerRef,
    chatDrawerOpen: context.chatDrawerOpen,
    chatPaneSize: context.chatPaneSize,
    activeChatSplitter: context.activeChatSplitter,
    currentUserId: context.session?.user.id ?? null,
    currentUserLabel: context.session?.user.display_name ?? 'You',
    comsParticipants: context.comsParticipants,
    rooms: context.rooms,
    roomUnreadCounts: context.roomUnreadCounts,
    selectedRoomId: context.selectedRoomId,
    selectedRoom: context.selectedRoom,
    messages: context.messages,
    activeCallRoomId: context.activeCallRoomId,
    callJoined: context.callJoined,
    callMediaMode: context.callMediaMode,
    screenSharing: context.screenSharing,
    remoteParticipants: context.remoteParticipants,
    localVideoRef: context.localVideoRef,
    onCreateRoom: (name: string, participantIds: string[]) => context.createRoom(name, participantIds),
    onCreateDirectRoom: (participantIds: string[]) => void context.createDirectRoom(participantIds),
    onDeleteRoom: context.deleteRoom,
    confirmRoomDelete: context.adminSettings?.confirm_file_delete ?? true,
    onRenameRoom: context.renameRoom,
    onUpdateRoomParticipants: context.updateRoomParticipants,
    onSelectRoom: context.setSelectedRoomId,
    onJoinVoiceCall: () => void context.joinCall('audio'),
    onJoinVideoCall: () => void context.joinCall('video'),
    onToggleScreenShare: () => void (context.screenSharing ? context.stopScreenShare() : context.startScreenShare()),
    onLeaveCall: context.leaveCall,
    onStartChatResize: () => context.setActiveChatSplitter(true),
    onToggleChatDrawer: () => context.setChatDrawerOpen((current: boolean) => !current),
    onSendMessage: context.sendMessage,
    onToggleMessageReaction: context.toggleMessageReaction,
  })

  const settingsPageProps = buildSettingsPageProps({
    appearance: context.appearance,
    shortcuts: context.shortcuts,
    orderedNavItems: context.orderedNavItems,
    session: context.session,
    canCustomizeAppearance: !context.adminSettings?.enforce_org_appearance && context.currentRolePolicy.customize_appearance,
    allowDirectCredentialChanges: context.adminSettings?.allow_user_credential_changes ?? true,
    onSetAppearance: context.setAppearance,
    onSetShortcuts: context.setShortcuts,
    onSetNavOrder: context.setNavOrder,
    onUploadAvatar: context.uploadCurrentUserAvatar,
    onUpdateCredentials: context.updateCurrentUserCredentials,
    onChangePassword: context.changeCurrentUserPassword,
    onLogout: context.logout,
  })

  const adminPageProps = buildAdminPageProps({
    isAdmin: context.currentRolePolicy.admin_panel,
    canManageUsers: context.currentRolePolicy.manage_users,
    canManageOrgSettings: context.currentRolePolicy.manage_org_settings,
    settings: context.adminSettings,
    users: context.adminUsers,
    storageOverview: context.adminStorageOverview,
    databaseOverview: context.adminDatabaseOverview,
    deletedItems: context.adminDeletedItems,
    auditEntries: context.adminAuditEntries,
    currentFontFamily: context.appearance.fontFamily,
    currentAccent: context.appearance.accent,
    currentPageGutter: context.appearance.pageGutter,
    currentRadius: context.appearance.radius,
    oidcConfig: context.oidc,
    systemUpdateStatus: context.systemUpdateStatus,
    onRefreshDatabaseOverview: () => void context.refreshAdminDatabaseOverview(),
    onRefreshDeletedItems: () => void context.refreshAdminDeletedItems(),
    onRefreshAuditEntries: () => void context.refreshAdminAuditEntries(),
    onRestoreDeletedItem: (id: string) => void context.restoreAdminDeletedItem(id),
    onSave: (settings: any) => void context.saveAdminSettings(settings),
    onRefreshSystemUpdateStatus: () => void context.refreshSystemUpdateStatus(),
    onRunSystemUpdate: () => void context.runSystemUpdate(),
    onApplyCurrentAppearance: () => {
      if (!context.adminSettings) return
      void context.saveAdminSettings({
        ...context.adminSettings,
        org_font_family: context.appearance.fontFamily,
        org_accent: context.appearance.accent,
        org_background: context.appearance.background,
        org_disable_gradients: context.appearance.disableGradients,
        org_gradient_top_left: context.appearance.gradientTopLeft,
        org_gradient_top_right: context.appearance.gradientTopRight,
        org_gradient_bottom_left: context.appearance.gradientBottomLeft,
        org_gradient_bottom_right: context.appearance.gradientBottomRight,
        org_gradient_strength: context.appearance.gradientStrength,
        org_page_gutter: context.appearance.pageGutter,
        org_radius: context.appearance.radius,
      })
    },
    onCreateUser: context.createAdminUser,
    onResetPassword: (userId: string, password: string) => void context.resetAdminUserPassword(userId, password),
    onUpdateUserAccess: (userId: string, payload: any) => void context.updateAdminUserAccess(userId, payload),
    onResolveCredentialRequest: (userId: string, approve: boolean) =>
      void context.resolveAdminUserCredentialRequest(userId, approve),
  })

  return {
    notesPageProps,
    filesPageProps,
    diagramsPageProps,
    voicePageProps,
    calendarPageProps,
    tasksPageProps,
    chatPageProps,
    settingsPageProps,
    adminPageProps,
  }
}
