export function buildSelectedEntityRuntimeContext({ appState, route, locationSearch, rooms, activeCallRoomId, session }: any) {
  return {
    notes: appState.notes,
    selectedNoteId: appState.selectedNoteId,
    diagrams: appState.diagrams,
    selectedDiagramId: appState.selectedDiagramId,
    route,
    locationSearch,
    rooms,
    selectedRoomId: appState.selectedRoomId,
    activeCallRoomId,
    memos: appState.memos,
    selectedVoiceMemoId: appState.selectedVoiceMemoId,
    session,
    selectedNoteRef: appState.selectedNoteRef,
    setNoteDraft: appState.setNoteDraft,
    selectedNoteIdRef: appState.selectedNoteIdRef,
    notesRef: appState.notesRef,
    setNotes: appState.setNotes,
    selectedFolderPathRef: appState.selectedFolderPathRef,
    persistedNoteStateRef: appState.persistedNoteStateRef,
    clientIdRef: appState.clientIdRef,
  }
}

export function buildAppSupportContext({
  appState,
  session,
  showActionNotice,
  displayNameForFileNodeFactory,
  diagramIdFromManagedPath,
  navOrder,
  roomUnreadCounts,
  appearance,
}: any) {
  return {
    session,
    setSession: appState.setSession,
    setAdminUsers: appState.setAdminUsers,
    setComsParticipants: appState.setComsParticipants,
    setMessages: appState.setMessages,
    setAdminSettings: appState.setAdminSettings,
    setAdminStorageOverview: appState.setAdminStorageOverview,
    setAdminDatabaseOverview: appState.setAdminDatabaseOverview,
    setAdminDeletedItems: appState.setAdminDeletedItems,
    setAdminAuditEntries: appState.setAdminAuditEntries,
    setSystemUpdateStatus: appState.setSystemUpdateStatus,
    setSetupStatus: appState.setSetupStatus,
    showActionNotice,
    displayNameForFileNodeFactory,
    notes: appState.notes,
    memos: appState.memos,
    diagrams: appState.diagrams,
    callJoined: appState.callJoined,
    remoteParticipants: appState.remoteParticipants,
    filesTree: appState.filesTree,
    selectedFilePath: appState.selectedFilePath,
    selectedVoiceMemo: appState.selectedVoiceMemo,
    selectedDiagramId: appState.selectedDiagramId,
    fileSearchQuery: appState.fileSearchQuery,
    activeFilePath: appState.activeFilePath,
    fileColumnWidths: appState.fileColumnWidths,
    fileColumnVisibility: appState.fileColumnVisibility,
    pendingDeletePaths: appState.pendingDeletePaths,
    adminSettings: appState.adminSettings,
    diagramIdFromManagedPath,
    navOrder,
    roomUnreadCounts,
    appearance,
  }
}

export function buildAppActionBundleContext({
  appState,
  session,
  route,
  supportBundle,
  selectedEntityRuntime,
  refreshFilesTree,
  syncNotesAndFilesView,
  showActionNotice,
  upsertVoiceMemo,
  createEntityId,
  normalizeFolderPath,
  mergeFolderPaths,
  defaultNoteTitle,
  noteIdFromPath,
  noteTitleFromPath,
  importedFolderForPath,
  editableHtmlToMarkdown,
  diagramIdFromManagedPath,
  deriveParentPath,
  diagramDisplayName,
  parseDrawioDiagramXml,
  findFileNode,
}: any) {
  return {
    createEntityId,
    memosRef: appState.memosRef,
    setMemos: appState.setMemos,
    setFilesTree: appState.setFilesTree,
    setSelectedVoiceMemoId: appState.setSelectedVoiceMemoId,
    refreshFilesTree,
    showActionNotice,
    upsertVoiceMemo,
    recording: appState.recording,
    mediaRecorderRef: appState.mediaRecorderRef,
    recordingStreamRef: appState.recordingStreamRef,
    recordingAudioContextRef: appState.recordingAudioContextRef,
    recordingAnalyserRef: appState.recordingAnalyserRef,
    recordingLevelFrameRef: appState.recordingLevelFrameRef,
    audioChunksRef: appState.audioChunksRef,
    speechRecognitionRef: appState.speechRecognitionRef,
    speechTranscriptRef: appState.speechTranscriptRef,
    setRecording: appState.setRecording,
    setVoiceInputLevel: appState.setVoiceInputLevel,
    setActionNotice: appState.setActionNotice,
    setStatus: appState.setStatus,
    api: appState.api,
    selectedNoteId: appState.selectedNoteId,
    notePresence: appState.notePresence,
    noteCursors: appState.noteCursors,
    session,
    clientIdRef: appState.clientIdRef,
    selectedRoomId: appState.selectedRoomId,
    callJoined: appState.callJoined,
    callMediaMode: appState.callMediaMode,
    localVideoRef: appState.localVideoRef,
    localStreamRef: appState.localStreamRef,
    screenStreamRef: appState.screenStreamRef,
    socketRef: appState.socketRef,
    activeCallRoomIdRef: appState.activeCallRoomIdRef,
    callJoinedRef: appState.callJoinedRef,
    rtcConfigRef: appState.rtcConfigRef,
    peerConnectionsRef: appState.peerConnectionsRef,
    setRemoteParticipants: appState.setRemoteParticipants,
    setActiveCallRoomId: appState.setActiveCallRoomId,
    setCallMediaMode: appState.setCallMediaMode,
    setScreenSharing: appState.setScreenSharing,
    setCallJoined: appState.setCallJoined,
    pushCallLog: appState.pushCallLog,
    notesRef: appState.notesRef,
    calendarConnections: appState.calendarConnections,
    calendarEvents: appState.calendarEvents,
    tasks: appState.tasks,
    route,
    noteEditorMode: appState.noteEditorMode,
    noteEditorRef: appState.noteEditorRef,
    noteDraftRef: appState.noteDraftRef,
    selectedNoteRef: appState.selectedNoteRef,
    selectedNoteIdRef: appState.selectedNoteIdRef,
    selectedFolderPathRef: appState.selectedFolderPathRef,
    persistedNoteStateRef: appState.persistedNoteStateRef,
    realtimeDraftBaseRef: appState.realtimeDraftBaseRef,
    locallyDirtyNoteIdsRef: appState.locallyDirtyNoteIdsRef,
    noteSavePromiseRef: appState.noteSavePromiseRef,
    noteDraftBroadcastTimeoutRef: appState.noteDraftBroadcastTimeoutRef,
    noteLiveSaveTimeoutRef: appState.noteLiveSaveTimeoutRef,
    pendingLiveSaveNoteIdRef: appState.pendingLiveSaveNoteIdRef,
    noteSaveState: appState.noteSaveState,
    notes: appState.notes,
    selectedFolderPath: appState.selectedFolderPath,
    setNoteDirtyVersion: appState.setNoteDirtyVersion,
    setNotePresence: appState.setNotePresence,
    setNoteSaveState: appState.setNoteSaveState,
    setNotes: appState.setNotes,
    setNoteDraft: appState.setNoteDraft,
    applySelectedNoteMarkdown: selectedEntityRuntime.applySelectedNoteMarkdown,
    setCustomFolders: appState.setCustomFolders,
    setSelectedNoteId: appState.setSelectedNoteId,
    setSelectedFolderPath: appState.setSelectedFolderPath,
    setRoute: appState.setRoute,
    normalizeFolderPath,
    mergeFolderPaths,
    defaultNoteTitle,
    noteIdFromPath,
    noteTitleFromPath,
    importedFolderForPath,
    editableHtmlToMarkdown,
    displayNameForFileNode: supportBundle.displayNameForFileNode,
    diagramsRef: appState.diagramsRef,
    selectedDiagram: selectedEntityRuntime.selectedDiagram,
    diagramDraft: appState.diagramDraft,
    diagramEditorMode: appState.diagramEditorMode,
    drawioEditorRef: appState.drawioEditorRef,
    setDiagrams: appState.setDiagrams,
    setSelectedDiagramId: appState.setSelectedDiagramId,
    setDiagramSourceFormat: appState.setDiagramSourceFormat,
    setDiagramDraft: appState.setDiagramDraft,
    setDiagramLoadVersion: appState.setDiagramLoadVersion,
    setDiagramEditorMode: appState.setDiagramEditorMode,
    diagrams: appState.diagrams,
    setCustomDiagramFolders: appState.setCustomDiagramFolders,
    diagramIdFromManagedPath,
    setRooms: appState.setRooms,
    setSelectedRoomId: appState.setSelectedRoomId,
    setCalendarConnections: appState.setCalendarConnections,
    setSelectedCalendarConnectionIds: appState.setSelectedCalendarConnectionIds,
    setTasks: appState.setTasks,
    setSelectedTaskId: appState.setSelectedTaskId,
    setCalendarEvents: appState.setCalendarEvents,
    messages: appState.messages,
    rooms: appState.rooms,
    comsParticipants: appState.comsParticipants,
    setMessages: appState.setMessages,
    noteContextRangeRef: appState.noteContextRangeRef,
    noteContextTableRef: appState.noteContextTableRef,
    noteContextCellRef: appState.noteContextCellRef,
    noteClipboardText: appState.noteClipboardText,
    setNoteClipboardText: appState.setNoteClipboardText,
    setNoteContextMenu: appState.setNoteContextMenu,
    setNoteContextSubmenu: appState.setNoteContextSubmenu,
    authMode: appState.authMode,
    setDeletedItems: appState.setDeletedItems,
    filesTree: appState.filesTree,
    fileRootNode: supportBundle.fileRootNode,
    setDiagramDrawerOpen: appState.setDiagramDrawerOpen,
    deriveParentPath,
    diagramDisplayName,
    parseDrawioDiagramXml,
    findFileNode,
    selectedFileNode: supportBundle.selectedFileNode,
    selectedFilePath: appState.selectedFilePath,
    activeFilePath: appState.activeFilePath,
    currentRolePolicy: supportBundle.currentRolePolicy,
    adminSettings: appState.adminSettings,
    newDriveFolderName: appState.newDriveFolderName,
    activeFileNode: supportBundle.activeFileNode,
    setNewDriveFolderName: appState.setNewDriveFolderName,
    setCreatingDriveFolder: appState.setCreatingDriveFolder,
    setSelectedFilePath: appState.setSelectedFilePath,
    setPendingDeletePaths: appState.setPendingDeletePaths,
    setRenamingFilePath: appState.setRenamingFilePath,
    setRenameFileName: appState.setRenameFileName,
    setConvertingFilePath: appState.setConvertingFilePath,
    setActiveFilePath: appState.setActiveFilePath,
    setMarkedFilePaths: appState.setMarkedFilePaths,
    syncNotesAndFilesView,
    currentDirectoryPath: supportBundle.currentDirectoryPath,
  }
}

export function buildAppPagePropsContext({
  appState,
  session,
  route,
  locationSearch,
  supportBundle,
  selectedEntityRuntime,
  actionBundle,
  routeActions,
  authActions,
  shareActions,
  noteTree,
  diagramTree,
  deletedItems,
  showActionNotice,
  refreshFilesTree,
  syncNotesAndFilesView,
  deleteSelectedNote,
  noteIdFromPath,
  noteTitleFromPath,
  diagramIdFromManagedPath,
  diagramIdFromPath,
  managedPathForNoteFolder,
  managedPathForDiagramFolder,
  managedPathForVoiceFolder,
  normalizeFolderPath,
  mergeFolderPaths,
  normalizeDiagramDirectoryPath,
  normalizeDiagramTitlePath,
  normalizeDiagramFolderPath,
  normalizeVoiceDirectoryPath,
  rebaseFolderEntries,
  getStandaloneDrawioUrl,
  handleTextareaTabKeyDown,
  beginNoteTreeDrag,
  handleNoteTreeDrop,
  beginDiagramTreeDrag,
  handleDiagramTreeDrop,
  beginVoiceTreeDrag,
  handleVoiceTreeDrop,
  beginFileColumnResize,
}: any) {
  return {
    route,
    locationSearch,
    session,
    ...appState,
    ...supportBundle,
    ...selectedEntityRuntime,
    ...actionBundle,
    ...routeActions,
    ...authActions,
    ...shareActions,
    noteTree,
    diagramTree,
    deletedItems,
    showActionNotice,
    refreshFilesTree,
    syncNotesAndFilesView,
    deleteSelectedNote,
    noteIdFromPath,
    noteTitleFromPath,
    diagramIdFromManagedPath,
    diagramIdFromPath,
    managedPathForNoteFolder,
    managedPathForDiagramFolder,
    managedPathForVoiceFolder,
    normalizeFolderPath,
    mergeFolderPaths,
    normalizeDiagramDirectoryPath,
    normalizeDiagramTitlePath,
    normalizeDiagramFolderPath,
    normalizeVoiceDirectoryPath,
    rebaseFolderEntries,
    getStandaloneDrawioUrl,
    handleTextareaTabKeyDown,
    beginNoteTreeDrag,
    handleNoteTreeDrop,
    beginDiagramTreeDrag,
    handleDiagramTreeDrop,
    beginVoiceTreeDrag,
    handleVoiceTreeDrop,
    beginFileColumnResize,
  }
}
